//
// Created by user on 29.08.2021.
//

#ifndef NEURALNETLIBRARY_BITMAPENCODINGS_H
#define NEURALNETLIBRARY_BITMAPENCODINGS_H

enum class BitmapEncodings{
    CCC,
};

#endif //NEURALNETLIBRARY_BITMAPENCODINGS_H
